### ISSUE TITLE
Update ms-rest dependency

### ISSUE THREAD

**Issue by bterlson** [Azure/amqp-common-js#27]
ms-rest and ms-rest-azure are deprecated and replaced by a combination of @azure/ms-rest-js, @azure/ms-rest-azure-js, @azure/ms-rest-nodeauth, and @azure/ms-rest-browserauth.

Updating this dependency should make it much easier for amqp-common and its dependents to be built for browsers.

**Comment by ramya-rao-a** [comment]
amqp-common, @azure/service-bus and @azure/event-hubs have all been updated to use @azure/ms-rest-nodeauth instead of ms-rest-azure

@AlexGhiondea, @bterlson do you want to keep this issue open to track similar work for the event processor host?

**Comment by AlexGhiondea** [comment]
I would create a new issue.
