### ISSUE TITLE
Service Bus - authorization token audience - aadServiceBusAudience 

### ISSUE THREAD

**Issue by HarshaNalluru** [Azure/amqp-common-js#30]
**aadEventHubsAudience**
* https://github.com/Azure/amqp-common-js/blob/c365c92aaa1b718a59859e2ec4a4361c6a68ae41/lib/util/constants.ts#L35
-----------------------
**authorization token audience**
* Inorder to work with EventHubs, `aadEventHubsAudience` needs to be imported from `@azure/amqp-common`[for authentication through `msrestAzure`]. 
[[EventHubs Sample](https://github.com/Azure/azure-event-hubs-node/blob/3c34bf0f3106dcf17a2088611f4854cab1ee9230/client/examples/sendReceiveWithInteractiveAuth.ts#L7)]    `aadEventHubsAudience = "https://eventhubs.azure.net/";`
* Just like the EventHubs, ServiceBus requires 
`aadServiceBusAudience = "https://servicebus.azure.net/";` [for authentication through `msrestAzure`].
* Just like the `aadEventHubsAudience`, amqp-common should provide `aadServiceBusAudience`.
------------------------ 
 
**Summary**
-  `export const aadServiceBusAudience = "https://servicebus.azure.net/";`
 Add the above line to `amqp-common-js/lib/util/constants.ts`
      
-------------------------
**More info**
 https://github.com/Azure/azure-sdk-for-js/pull/1202#issuecomment-463472212

**Comment by AlexGhiondea** [comment]
@HarshaNalluru is this issue about adding a constant string in the constants file?

**Comment by HarshaNalluru** [comment]
Yes @AlexGhiondea
