### ISSUE TITLE
Parameter validations for amqp-common

### ISSUE THREAD

**Issue by ShivangiReja** [Azure/amqp-common-js#48]
Parameter validations for amqp-common:
- Remove all the type checks for partitionId in [createFromConnectionConfig](https://github.com/Azure/amqp-common-js/blob/master/lib/connectionConfig/eventhubConnectionConfig.ts#L95) operation. Service gives a nice meaningful error for invalid partitionId when send/receive data.
- Don't need a type check for [connectionId ](https://github.com/Azure/amqp-common-js/blob/master/lib/retry.ts#L83) in [validateRetryConfig ](https://github.com/Azure/amqp-common-js/blob/master/lib/retry.ts#L77)operation.
- Coerce given input to string
   -  ConnectionConfig properties in [validate operation](https://github.com/Azure/amqp-common-js/blob/master/lib/connectionConfig/connectionConfig.ts#L113).
   - IotHubConnectionConfig properties in [validate operation](https://github.com/Azure/amqp-common-js/blob/master/lib/connectionConfig/iothubConnectionConfig.ts#L78).
   - RetryConfig properties in [validateRetryConfig ](https://github.com/Azure/amqp-common-js/blob/master/lib/retry.ts#L77)operation.
   - connectionString in [create connection config](https://github.com/Azure/amqp-common-js/blob/master/lib/connectionConfig/connectionConfig.ts#L86)  operation.
  - connectionString in [create connection config ](https://github.com/Azure/amqp-common-js/blob/master/lib/connectionConfig/iothubConnectionConfig.ts#L53)operation(Iot).
  - connectionString in [isIotHubConnectionString ](https://github.com/Azure/amqp-common-js/blob/master/lib/util/utils.ts#L249)operation.

**Comment by ramya-rao-a** [comment]
Completed with https://github.com/Azure/amqp-common-js/pull/51
