### ISSUE TITLE
Non-amqp and non-system errors should not be retryable by default

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/amqp-common-js#49]
For amqp and system errors, we check the list of [retryableErrors](https://github.com/Azure/amqp-common-js/blob/f97396645ea07fe59ab6f45ce9abb413fb9e9bbe/lib/errors.ts#L486) to determine whether the error is retryable or not.

But all other errors are deemed as retryable without this check. See the below code in `translate()` method.

https://github.com/Azure/amqp-common-js/blob/f97396645ea07fe59ab6f45ce9abb413fb9e9bbe/lib/errors.ts#L566-L570
@amarzavery Was this intentional or a miss?

If there was any error in rhea (not due to the service or network, but actual errors coming from rhea, for example: TypeError), it would get marked as retryable due to the above.

**Comment by ramya-rao-a** [comment]
cc @AlexGhiondea, @bterlson

**Comment by amarzavery** [comment]
This was done intentionally. Initially everything was non retryable by default. However, that caused issues in eventhub, where the link was not being recovered on failure. SJ, recommended that everything should be retryable by default and we should maintain a list of errors that shouldn't be retryable. Hence this design.

**Comment by ramya-rao-a** [comment]
In that case, I want to exclude `TypeError` from the list of retryable errors. Thoughts?

**Comment by bterlson** [comment]
Could possibly add RangeError to the exclusion list as well?

**Comment by amarzavery** [comment]
Yup, adding `TypeError` and `RangeError` to the exclusion list would be the right thing to do in the current design.

However there is no exclusion list per se. 

The situation is very similar to `SystemError`. I wanted to retry on some of the SystemErrors. Thus, created a category for it.
Added [SystemError](https://github.com/Azure/amqp-common-js/blob/f97396645ea07fe59ab6f45ce9abb413fb9e9bbe/lib/errors.ts#L240) to `ErrorNameConditionMapper` and `ConditionErrorNameMapper` enums.

We can create one more category let's say `ClientValidationError` (or some other logical name) and define a function `isClientValidationError()` which currently checks for `TypeError`and `RangeError`. In the future it can check for other errors as necessary. If it is a `ClientValidationError` then we can set the retryable property of the MessagingError to be false as done for SystemError over [here](https://github.com/Azure/amqp-common-js/blob/f97396645ea07fe59ab6f45ce9abb413fb9e9bbe/lib/errors.ts#L553-L565).

**Comment by ramya-rao-a** [comment]
I am also not comfortable in converting such errors to a `MessagingError`. They should retain their type.

I would suggest the changes in #51

**Comment by ramya-rao-a** [comment]
Fixed with #51
