### ISSUE TITLE
Add tests to cover all errors being thrown

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/amqp-common-js#55]
As part of https://github.com/Azure/amqp-common-js/pull/50, we changed a lot of errors that were being thrown.

This issue is to track the corresponding work to be done in the tests, so that all these errors get test coverage 

cc @ShivangiReja

**Comment by ShivangiReja** [comment]
Following tests are missing:
- All tests are missing for [validate operation](https://github.com/Azure/amqp-common-js/blob/master/lib/connectionConfig/connectionConfig.ts#L112), where we validate the properties of connection config(Same for iothubConnectionConfig and retry config)
- Test case is missing when user-agent string length is greater than maxUserAgentLength (https://github.com/Azure/amqp-common-js/blob/master/lib/ConnectionContextBase.ts#L138)

**Comment by ramya-rao-a** [comment]
@ShivangiReja Let's add the tests for all the cases you have listed.
I believe we can use `context.spec.ts` for adding the test for user agent, and `config.spec.ts` for the rest

**Comment by ramya-rao-a** [comment]
Fixed with #57
