### ISSUE TITLE
ts-node ./examples/receive.ts 

### ISSUE THREAD

**Issue by qiannianshaonian** [Azure/amqp-common-js#56]
import * as tslib_1 from "tslib";
       ^

SyntaxError: Unexpected token *
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Module.m._compile (/usr/local/lib/node_modules/ts-node/src/index.ts:439:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/usr/local/lib/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)

why?

**Comment by qiannianshaonian** [comment]
ts-node ./examples/cbsAuth.ts
Same problem

**Comment by qiannianshaonian** [comment]
can you give me some document  of this sdk, some param is set up anywhere , i can get it but is not easily

**Comment by bterlson** [comment]
Our tsconfig is configured to emit es6 modules which doesn't work well with ts-node. If you override that setting on the command line, ts-node should work. Try: `ts-node -O '{ "module": "commonjs" }'`.

I'm not sure I follow your last question, can you please restate?

**Comment by qiannianshaonian** [comment]
{
  "compilerOptions": {
    "module": "es6",
    "lib": [],
    "preserveConstEnums": true,
    "sourceMap": true,
    "newLine": "LF",
    "target": "es6",
    "importHelpers": true,
    "moduleResolution": "node",
    "noImplicitReturns": true,
    "outDir": "dist-esm",
    "allowJs": false,
    "esModuleInterop": true,
    "noUnusedLocals": true,
    "strict": true,
    "declaration": true,
    "declarationDir": "./typings",
    "declarationMap": true
  },
  "compileOnSave": true,
  "exclude": [
    "node_modules",
    "testhub",
    "typings/**",
    "processor"
  ],
  "include": [
    "./lib/**/*.ts",
    "./tests/**/*.ts",
    "./examples/**/*.ts"
  ]
}

ts-node ./examples/receive.ts
but error same

**Comment by qiannianshaonian** [comment]
git clone https://github.com/Azure/amqp-common-js.git
the tsconfig  is configured to emit es2015 modules
my node version is v10.15.3

**Comment by bterlson** [comment]
@qiannianshaonian the tsconfig is correct; we emit es2015 modules which are further processed by rollup into the final node and browser artifacts. You need to override that setting for ts-node to work as I showed above.

**Comment by ramya-rao-a** [comment]
Closing this issue as we havent heard back from @qiannianshaonian after @bterlson's suggestions
