### ISSUE TITLE
Rhea's TypeErrors which are not of TypeError instance should also not be translated

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/amqp-common-js#58]
#49 covers the issue of "Non-amqp and non-system errors should not be retryable by default"

Rhea uses normal Errors (not TypeError) for the case of TypeErrors.
See https://github.com/amqp/rhea/blob/master/lib/errors.js#L27

To handle such cases, we need to update the below `if` check to include `|| err.name === "TypeError"`
https://github.com/Azure/amqp-common-js/blob/e8608c45934373a65066a9d628b9c808f2ede1cb/lib/errors.ts#L532-L535

**Comment by ramya0820** [comment]
Since the repository is now moved to https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/core/amqp
This issue is now tracked at Azure/azure-sdk-for-js#2707 instead.
