### ISSUE TITLE
Fails to build under TypeScript due to missing async-lock definition

### ISSUE THREAD

**Issue by nebrius** [Azure/amqp-common-js#59]
**Describe the bug**
When building a TypeScript project that uses @azure/amqp-common (in my case a dependency of @azure-event-hubs), I get the following error:

```
node_modules/@azure/amqp-common/typings/lib/util/utils.d.ts:1:23 - error TS7016: Could not find a declaration file for module 'async-lock'. '/mnt/c/Users/nebri/Projects/aquarium-control/server/node_modules/async-lock/index.js' implicitly has an 'any' type.
  Try `npm install @types/async-lock` if it exists or add a new declaration (.d.ts) file containing `declare module 'async-lock';`

1 import AsyncLock from "async-lock";
```

When I install the @types/async-lock module (which should _not_ be necessary as an end-user), I then get the following error:

```
node_modules/@azure/amqp-common/typings/lib/util/utils.d.ts:1:8 - error TS1192: Module '"/mnt/c/Users/nebri/Projects/aquarium-control/server/node_modules/@types/async-lock/index"' has no default export.

1 import AsyncLock from "async-lock";
```

**To Reproduce**

Install "@azure/event-hubs": "^2.0.0" and "typescript": "^3.4.5". Use this tsconfig:

```
{
  "include": [
    "src/**/*.ts"
  ],
  "compilerOptions": {
    /* Basic Options */
    "target": "esnext",                          /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', or 'ESNEXT'. */
    "module": "commonjs",                     /* Specify module code generation: 'none', commonjs', 'amd', 'system', 'umd', 'es2015', or 'ESNext'. */
    "sourceMap": true,                        /* Generates corresponding '.map' file. */
    "declaration": true,
    "declarationDir": "declarations",
    "outDir": "./dist",
    "rootDir": "./src",

    /* Strict Type-Checking Options */
    "strict": true,                           /* Enable all strict type-checking options. */
    "noImplicitAny": true,                    /* Raise error on expressions and declarations with an implied 'any' type. */
    "strictNullChecks": true,                 /* Enable strict null checks. */
    "noImplicitThis": true,                   /* Raise error on 'this' expressions with an implied 'any' type. */
    "alwaysStrict": true,                     /* Parse in strict mode and emit "use strict" for each source file. */

    /* Additional Checks */
    "noUnusedLocals": true,
    "noImplicitReturns": true
  }
}
```

**Expected behavior**
This should compile without errors

**Package-version**:  ` @azure/amqp-common@1.0.0-preview.3` (why is the production version of @azure/event-hubs@2.0.0 installing a preview version of amqp-common?)

**node.js version**: 10.15.3

**OS name and version**: Windows 10 64-bit, via WSL with Ubuntu

**Additional context**

**Comment by bterlson** [comment]
Two issues here:

The former error is because `@types/async-lock` [is a dev dep](https://github.com/Azure/amqp-common-js/blob/master/package.json#L35) but should be a normal dep. This needs to be fixed.

The latter error is likely due to your config lacking the TS `esModuleInterop` or `allowSyntheticDefaultImports` setting. This needs to be documented ala [ServiceBus](https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/servicebus/service-bus#configure-typescript).

**Comment by nebrius** [comment]
Thanks for the info @bterlson 

FYI I cannot use the `esModuleInterop` flag as it breaks other packages I'm using. If it's broken for me, we _probably_ shouldn't be recommending it to our users. That said, `allowSyntheticDefaultImports` worked, so perhaps an explainer of the dangers of using `esModuleInterop`?

Related: I'm still curious about why a preview version of amqp-common is installed with the production version of event-hubs. It may not be a big deal, but without context into the specifics it sounds disconcerting. Any insight?

**Comment by ramya0820** [comment]
Since the repository is now moved to https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/core/amqp
This issue is now tracked at https://github.com/Azure/azure-sdk-for-js/issues/2706 instead.
